In [1]:
import torch

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [9]:
x = torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
X = x.reshape(3,4)
X

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [11]:
X.shape

torch.Size([3, 4])

In [12]:
Y = x.reshape(3,-1)
Y

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [13]:
Z = x.reshape(-1,4)
Z

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [14]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
torch.randn(3,4)

tensor([[-0.6288,  1.5340,  1.1623,  0.9261],
        [ 0.2594, -1.6423, -0.1584, -0.8151],
        [-1.1804,  0.2356,  0.7228, -1.7276]])

In [17]:
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [20]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
z = torch.tensor([1,2,4,8])

In [19]:
x+y

tensor([ 3.,  4.,  6., 10.])

In [21]:
y+z

tensor([ 3,  4,  6, 10])

In [22]:
x/y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [23]:
x*y

tensor([ 2.,  4.,  8., 16.])

In [24]:
x**y

tensor([ 1.,  4., 16., 64.])

In [25]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [31]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [32]:
x.sum()

tensor(66.)

In [34]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [36]:
z = x.reshape(3,1)+y
z

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

In [37]:
x[-1]

tensor(3)

In [39]:
x[0:2]

tensor([1, 2])

In [40]:
z[1,2] = 9
z

tensor([[5, 6, 7],
        [6, 7, 9],
        [7, 8, 9]])

In [41]:
z[0:2,0:2]=12
z

tensor([[12, 12,  7],
        [12, 12,  9],
        [ 7,  8,  9]])

In [43]:
id(x),id(y)

(1844245874112, 1844246058560)

In [44]:
#节省内存
a = id(y)
y = x+y
id(y)==a

False

In [46]:
b = id(a)
a = id(y)
y[:] = x +y
id(y) == a,id(a) == b

(True, False)

In [47]:
z

tensor([[12, 12,  7],
        [12, 12,  9],
        [ 7,  8,  9]])

In [48]:
z.numpy()

array([[12, 12,  7],
       [12, 12,  9],
       [ 7,  8,  9]], dtype=int64)

In [49]:
type(z.numpy())

numpy.ndarray

In [50]:
type(z)

torch.Tensor

In [52]:
a = torch.tensor(3.5)
a,a.item(),float(a),int(a)

(tensor(3.5000), 3.5, 3.5, 3)

In [53]:
type(a.item())

float

In [54]:
a == a.item()

tensor(True)

In [55]:
import os
import pandas as pd

In [56]:
os.getcwd()

'D:\\Codes\\python\\re0pytorch'

In [57]:
os.path

<module 'ntpath' from 'D:\\Anaconda3\\envs\\torch102\\lib\\ntpath.py'>

In [59]:
os.makedirs(os.path.join('.','data'),exist_ok=True)
data_file = os.path.join('.','data','house_tiny.csv')

In [60]:
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('NA,NA,140000\n')

In [62]:
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       NaN   NaN  140000


In [67]:
inputs = data.iloc[:,:2]
outputs = data.iloc[:,2]
inputs,outputs

(   NumRooms Alley
 0       NaN  Pave
 1       2.0   NaN
 2       NaN   NaN,
 0    127500
 1    106000
 2    140000
 Name: Price, dtype: int64)

In [68]:
inputs = pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       NaN           1          0
1       2.0           0          1
2       NaN           0          1


In [69]:
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  Alley_Pave  Alley_nan
0       2.0           1          0
1       2.0           0          1
2       2.0           0          1

In [71]:
X,y = torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[2., 1., 0.],
         [2., 0., 1.],
         [2., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 140000]))

In [73]:
A = torch.arange(0,20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [74]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [75]:
B = A.clone()
id(A)==id(B)

False

In [80]:
B = torch.ones(A.shape)
B

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [81]:
B += B
B

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [82]:
A * B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [90]:
A.sum(axis=0),A.sum(axis=1)

(tensor([40, 45, 50, 55]), tensor([ 6, 22, 38, 54, 70]))

In [96]:
y = torch.ones(4,dtype=torch.float32)
x = torch.arange(4,dtype=torch.float32)
x,y

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]))

In [97]:
torch.dot(x,y)

tensor(6.)

In [102]:
A = A.float()
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [106]:
torch.matmul(A,B.T)

tensor([[ 12.,  12.,  12.,  12.,  12.],
        [ 44.,  44.,  44.,  44.,  44.],
        [ 76.,  76.,  76.,  76.,  76.],
        [108., 108., 108., 108., 108.],
        [140., 140., 140., 140., 140.]])

In [107]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([1,2,3,4])

In [108]:
torch.matmul(x.T,y)

tensor(30)

In [109]:
torch.dot(x,y)

tensor(30)

In [110]:
u = torch.tensor([3.,-4])
torch.norm(u)

tensor(5.)

In [112]:
torch.abs(u).sum()

tensor(7.)

In [117]:
x = torch.arange(4.)
x

tensor([0., 1., 2., 3.])

In [119]:
x.requires_grad_(True)
x.grad

In [120]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [122]:
y.backward()

In [123]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [124]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [130]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [131]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

In [132]:
x.grad.zero_()
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [137]:
x.grad.zero_()
y = x * x
z = y * x
z

tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)

In [138]:
z.sum().backward()
x.grad

tensor([ 0.,  3., 12., 27.])

In [134]:
x

tensor([0., 1., 2., 3.], requires_grad=True)